broker:
  ip: "spare-c2e38-30-04"
  port: 31883

rabbitmq:
  replicas: 3
  name: rabbit-cluster
  log: "debug"
  queue:
    type: "quorum"
    max_length: 100000
  plugins:
    - rabbitmq_mqtt
  root:
    user: "guest"
    password: "guest"
  client:
    username: "user"
    password: "password"
  node:
    hostnames:
      - "d3vrubu-c2e34-10-01"
      - "d3vrubu-c2e34-12-01"
      - "d3vrubu-c2e34-14-01"
      - "d3vrubu-c2e34-16-01"
      - "d3vrubu-c2e34-18-01"
      - "d3vrubu-c2e34-29-01"
      - "d3vrubu-c2e34-31-01"
      - "d3vrubu-c2e34-33-01"
      - "d3vrubu-c2e34-35-01"
  nodeport:
    mqtt: 31883
    management: 31567
    amqp: 30567

producer:
  version: 0.0.1.3
  name: "benchmark-producer-job"
  instances:
    total: 2
    parallel: 2
  flags:
    '
    --fresh 
    --period 0 
    --min 72 
    --max 72 
    --username user 
    --password password 
    --qos 1 
    --messages 10000000
    '
  path: "~/data"
  init_timeout: 600
  node:
    hostnames:
      - "d3vrubu-c2e34-10-01"
      - "d3vrubu-c2e34-12-01"
      - "d3vrubu-c2e34-14-01"
      - "d3vrubu-c2e34-16-01"
      - "d3vrubu-c2e34-18-01"
      - "d3vrubu-c2e34-29-01"
      - "d3vrubu-c2e34-31-01"
      - "d3vrubu-c2e34-33-01"
      - "d3vrubu-c2e34-35-01"

consumer:
  version: 0.0.1.3
  name: "benchmark-consumer-job"
  instances:
    total: 1
    parallel: 1
  flags:
    '
    --username user 
    --password password 
    --qos 1 
    --duration 100 
    --ratio 80 
    --fresh
    '
  path: "~/data"
  init_timeout: 600
  node:
    hostnames:
      - "d3vrubu-c2e34-10-01"
      - "d3vrubu-c2e34-12-01"
      - "d3vrubu-c2e34-14-01"
      - "d3vrubu-c2e34-16-01"
      - "d3vrubu-c2e34-18-01"
      - "d3vrubu-c2e34-29-01"
      - "d3vrubu-c2e34-31-01"
      - "d3vrubu-c2e34-33-01"
      - "d3vrubu-c2e34-35-01"
