broker: spare-c2e38-30-04
port: 31883

rabbitmq:
  replicas: 3
  username: user
  password: password
  nodeport:
    mqtt: 31883
    management: 31567
    amqp: 30567

producer:
  version: 0.0.0.5
  name: benchmark-producer-job
  instances:
    total: 2
    parallel: 2
  flags:
    '[
    "--fresh",
    "--period", "0",
    "--min", "72",
    "--max", "72",
    "--username", "user",
    "--password", "password",
    "--qos", "1",
    "--messages", "10000000"
    ]'
  path: /nfshome0/dkosc/data
  init_timeout: 600

consumer:
  version: 0.0.0.5
  name: benchmark-consumer-job
  instances:
    total: 1
    parallel: 1
  flags:
    '[
    "--username", "user",
    "--password", "password",
    "--qos", "1",
    "--duration", "100",
    "--ratio", "80",
    "--fresh"
    ]'
  path: /nfshome0/dkosc/data
  init_timeout: 600
