apiVersion: batch/v1
kind: Job
metadata:
  name: benchmark-consumer-job
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
        - name: benchmark-producer
          image: gitlab-registry.cern.ch/cmsos/k8sbox/rabbitmq/cmsos-x86_64-rabbitmq:0.0.0.5
          env:
            - name: BROKER_IP
              value: "spare-c2e38-30-04"
            - name: MQTT_PORT
              value: "30150"
          volumeMounts:
            - mountPath: /data
              name: data-volume
          command: [ "/opt/benchmark/bin/consumer" ]
          args: [
            "--username", "username",
            "--password", "password",
            "--qos", "1",
            "--separators", "4",
            "--directory", "data",
            "-f"
          ]
      volumes:
        - name: data-volume
          hostPath:
            path: /nfshome0/dkosc/data
      restartPolicy: Never