apiVersion: batch/v1
kind: Job
metadata:
  name: benchmark-consumer-job
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: job-name
                      operator: In
                      values:
                        - benchmark-consumer-job
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: benchmark-consumer
          image: gitlab-registry.cern.ch/cmsos/k8sbox/rabbitmq/cmsos-x86_64-rabbitmq:0.0.1.1
          env:
            - name: BROKER_IP
              value: "spare-c2e38-30-04"
            - name: MQTT_PORT
              value: "31883"
          volumeMounts:
            - mountPath: /data
              name: data-volume
          command: [ "/opt/benchmark/bin/consumer" ]
          args: [
            "--username", "user",
            "--password", "password",
            "--qos", "1",
            "--duration", "100",
            "--ratio", "80",
          ]
      volumes:
        - name: data-volume
          hostPath:
            path: ~/data
      restartPolicy: Never