apiVersion: batch/v1
kind: Job
metadata:
  name: benchmark-producer-job
spec:
  completions: 2
  parallelism: 2
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: job-name
                      operator: In
                      values:
                        - benchmark-producer-job
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: benchmark-producer
          image: gitlab-registry.cern.ch/cmsos/k8sbox/rabbitmq/cmsos-x86_64-rabbitmq:0.0.0.9
          env:
            - name: BROKER_IP
              value: "spare-c2e38-30-04"
            - name: MQTT_PORT
              value: "31883"
          volumeMounts:
            - mountPath: /data
              name: data-volume
          command: ["/opt/benchmark/bin/producer"]
          args: [
            "--period", "0",
            "--min", "72",
            "--max", "72",
            "--username", "user",
            "--password", "password",
            "--qos", "1",
            "--messages", "10000000"
          ]
      volumes:
        - name: data-volume
          hostPath:
            path: /nfshome0/dkosc/data
      restartPolicy: Never