apiVersion: batch/v1
kind: Job
metadata:
  name: benchmark-producer-job
spec:
  completions: 2
  parallelism: 2
  template:
    spec:
      containers:
        - name: benchmark-producer
          image: gitlab-registry.cern.ch/cmsos/k8sbox/rabbitmq/cmsos-x86_64-rabbitmq:0.0.0.5
          env:
            - name: BROKER_IP
              value: "spare-c2e38-30-04"
            - name: MQTT_PORT
              value: "30150"
          volumeMounts:
            - mountPath: /data
              name: data-volume
          command: ["/opt/benchmark/bin/producer"]
          args: ["--period", "0",
                 "--min", "1",
                 "--max", "8192",
                 "--username", "default_user_IA25ZnsK4W-fVt5dqAk",
                 "--password", "Mmsq35eOrI_iFNpl7uIPAXPX17B73pAs",
                 "--qos", "1",
                 "--messages", "1000"]
      volumes:
        - name: data-volume
          hostPath:
            path: /nfshome0/dkosc/data
      restartPolicy: Never