apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbit-cluster
spec:
  replicas: 3
  service:
    type: NodePort
  image: rabbitmq:3.12-management
  rabbitmq:
    additionalConfig: |
      log.console.level = debug 
      mqtt.default_user = user
      mqtt.default_pass = password
    additionalPlugins:
      - rabbitmq_mqtt