apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.consumer.name }}
spec:
  completions: {{ .Values.consumer.instances.total }}
  parallelism: {{ .Values.consumer.instances.parallel }}
  template:
    spec:
      containers:
        - name: benchmark-producer
          image: gitlab-registry.cern.ch/cmsos/k8sbox/rabbitmq/cmsos-x86_64-rabbitmq:{{ .Values.consumer.version }}
          env:
            - name: BROKER_IP
              value: {{ .Values.broker }}
            - name: MQTT_PORT
              value: {{ .Values.port }}
          volumeMounts:
            - mountPath: /data
              name: data-volume
          command: ["/opt/benchmark/bin/consumer"]
          args: {{ .Values.consumer.flags }}
      volumes:
        - name: data-volume
          hostPath:
            path: {{ .Values.consumer.path }}
      restartPolicy: Never
